//go:build darwin

// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.554001 +0100 BST m=+1.174038334. DO NOT EDIT.

package vk

// CAMetalLayer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/CAMetalLayer.html
type CAMetalLayer struct{}
