// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.540769 +0100 BST m=+1.160805668. DO NOT EDIT.

package vk

// MetalSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateFlagsEXT.html
type MetalSurfaceCreateFlagsEXT Flags
