// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.693886 +0100 BST m=+1.313927709. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
