// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.568012 +0100 BST m=+1.188049293. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
