// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.777673 +0100 BST m=+1.397718334. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
