// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.513976 +0100 BST m=+1.134012001. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT StructureType = 1000217000
)
