//go:build darwin

// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.527571 +0100 BST m=+1.147606793. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
