//go:build darwin

// Code generated by go-vk from vk.xml at 2026-10-08 22:06:31.680817 +0100 BST m=+1.300858834. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
